# Generated by Django 4.2 on 2024-07-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
